FROM node:16-alpine
WORKDIR /app

ENV PORT 3000
ENV HOST 0.0.0.0
ENV VITE_PREDICT_URL=d"127.0.0.1:8000/predict"

COPY package*.json ./

RUN npm install

COPY . .

# Expose the container port
EXPOSE 3000

CMD ["npm", "run", "dev"]
